import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Link from "next/link";
import { ConnectButton } from "arweave-wallet-kit";
import { Button, Space, Image, Layout, Row, Avatar, theme } from "antd";
const { Header, Footer, Sider, Content } = Layout;
import logoImg from "../public/batman-icon.png";
import Gallery from "@/components/Gallery";
import { customTheme } from "@/config";

const inter = Inter({ subsets: ["latin"] });

const { getDesignToken, useToken } = theme;

const globalToken = getDesignToken(customTheme);

const headerStyle: React.CSSProperties = {
  height: 54,
  lineHeight: "54px",
  backgroundColor: globalToken.colorBgBase,
  color: "black",
  boxShadow: "0 2px 3px -2px rgba(0,0,0,0.3)",
};

const contentStyle: React.CSSProperties = {
  minHeight: "calc(100vh - 54px)",
  padding: 16,
};

export default function Home() {
  const { token } = useToken();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Layout>
          <Header style={headerStyle}>
            <Row justify="space-between" align="middle">
              <Image
                width="38px"
                src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAACXBIWXMAAA7EAAAOxAGVKw4bAAAC+UlEQVRYw7WXS0iUURTHfzNRWZGjQbWy0pKyhZmJi15gQbQqaiM9aBFkFj1oF22koEVUi4oWYQ/SIgqiIip6Qi+QoAdWJmgaBMVo2dOyZJw2/4mPz3Nn5hv1wmVm7v/ce8499/zPORNiYGMsUAJMAbKBVuAmQzxGA1XAA6AXiPvm8aFSHAKqgaih1Dv75JFBHROAuykUe+f0wVReALQFUH4rqFtT3bwByE8i0wY8AzqAZsXA78F6c5fbY0A9MGsoo73aoTwKLJJMGNgLtAPvgafAWWAzkDdQqkUdyr0Bti1JLMSA68C8TAzY6DiwQvgKfV5KIyj79Fw5QQx4aBxU53mal/q+JwA73gIz0lGe7chwxUAE+KJblQJjgCv6nY4RHUBRKgMWGBtbhW3wrL0GJmo9ouxXAdQALUmMaAfGJTNgnbHpvLB640Y1wBKg3HNwGFgPdDmMuJDMgC3GhiPC7qVwcQx4BCyX/FSHN/qAxUH4f0zYjQBBdw7I0tN0Gvh9lwErDeHbwg4GMCAumoaASocXTFbMNIS/6zYLAxoQVyygeuHHdloGhIFPhvAa4Y/TTD4fRNlWecGKrWuuZzhlCDfpoNUpFNf66sB8IFf898u/SwjNUZuVqG5zHQrygNlJDNin/ZMUzMuAYVobbiSsHoBNHiCmSoZRiruAkcBSh/JG4SWKmcT6VY83/hq07Vf1ulXxCuT2uN4ywe06hyvzZcBzAy9VivevfwP4agBv1A2FxOMsKV8lq71vflEpOaxewPJOmYNBjQD7HZtafB1PPnAGuANcViUsFpajNeucBl3kgIGdTjQfzY7Nf5SGCx1siQBbRTlrf7fySgT4bOBrEwcVJSkcCVc3Kb0eBU4q5/ekqAuVOn+7gf9QXPwf5Y4ElMns9WRAgN2GzGHLpYXAiwEqj6o8+9P7L49Mp6eX6DdGALtEkaC3rgXGO84tA04Ah4Bp6bRmOcAO4ImPev7YaFZrntH/wVCacrmi5GRgFPAT+Ai8ksszHv8A8LIPt8fFsuoAAAAASUVORK5CYII="
                alt="logo"
                style={{ borderRadius: "50%" }}
                preview={false}
              />
              <ConnectButton
                accent={token.colorPrimary}
                style={{
                  height: "34px",
                }}
              />
            </Row>
          </Header>
          <Content style={contentStyle}>
            <Gallery />
          </Content>
        </Layout>
      </main>
    </>
  );
}
